"""USE STYLES FOLDER FILES TO DECREASE CODE SIZE HERE.
CHECKOUT GUIDES FOR RESPONSIVE DESIGN"""

import reflex as rx
from personal_sp_portfolio.styles import styles, colors, sizes

def navbar():
    return rx.hstack(
        rx.hstack(
            rx.heading("Matias Morcos", font_size="min(5vw, 30px)"),
            marginRight="1em",
            color="white",
            fontWeight="semibold",
            #text_shadow="4px 8px 12px white",
            text_border="2px solid black",
        ),
        rx.hstack(
            rx.link(
                "Home",
                href="/",
                color="white",
                marginRight="1em",
                text_shadow="2px 2px 2px white",
                _hover={"color": "white"},
            ),
            #rx.link(
            #    "About me",
            #    href="#about",
            #    color="white",
            #    marginRight="1em",
            #    text_shadow="2px 2px 2px white",
            #),
            rx.link(
                "Projects",
                href="#projects",
                color="white",
                fontWeight="semibold",
                marginRight="1em",
                text_shadow="2px 2px 2px white",
                _hover={"color": "white"},
            ),
            # rx.menu.root(
            #     rx.menu.trigger(
            #         rx.link(
            #             "Projects",
            #             href="#projects",
            #             color="white",
            #             fontWeight="semibold",
            #             marginRight="1em",
            #             text_shadow="4px 8px 10px white",
            #             background_color="rgba(0, 0, 0, 0)",
            #             backdrop_filter= "blur(50px)",
            #         ),
            #     ),
            #     rx.menu.content(
            #         rx.menu.item(
            #             rx.link(
            #                 "Users Management System for Booking App",
            #                 href="icl1",
            #                 color="white",
            #                 fontWeight="semibold",
            #                 marginRight="1em",
            #                 background_color="rgba(0, 0, 0, 0)",
            #                 text_shadow="4px 8px 10px white",
            #                 backdrop_filter= "blur(50px)",
            #             ),
            #         ),
            #         rx.menu.item(
            #             rx.link(
            #                 "Temporary Rental Form Builder",
            #                 href="rental",
            #                 color="white",
            #                 fontWeight="semibold",
            #                 marginRight="1em",
            #                 background_color="rgba(0, 0, 0, 0)",
            #                 text_shadow="4px 8px 10px white",
            #                 backdrop_filter= "blur(50px)",
            #             ),
            #         ),
            #         rx.menu.item(
            #             rx.link(
            #                 "Payment Agreement Builder",
            #                 href="agreements",
            #                 color="white",
            #                 fontWeight="semibold",
            #                 marginRight="1em",
            #                 background_color="rgba(0, 0, 0, 0)",
            #                 text_shadow="4px 8px 10px white",
            #                 backdrop_filter= "blur(50px)",
            #             ),
            #         ),
            #         width="25rem",
            #         background_color="rgba(0, 0, 0, 0)",
            #         backdrop_filter= "blur(50px)",
            #     ),
            # ),
            rx.link(
                "Resume",
                href="#resume",
                color="white",
                marginRight="1em",
                text_shadow="2px 2px 2px white",
                _hover={"color": "white"},
            ),
            #rx.link(
            #    "Contact",
            #    href="#contact",
            #    color="white",
            #    marginRight="1em",
            #    text_shadow="2px 2px 2px white",
            #),
            rx.link(rx.image(src="github.png", radius="full"),
                href="https://github.com/matimorcos",
                target="_blank",
                marginRight="0.5em",
                maxWidth="48px",
                width="100%",
                maxHeight="48px",
                height="100%",
                align="center",
            ),
            rx.link(
                rx.image(src="linkedin.png", radius="full"),
                href="https://www.linkedin.com/in/matias-morcos-mm/",
                target="_blank",
                marginRight="0.5em",
                maxWidth="48px",
                width="100%",
                maxHeight="48px",
                height="100%",
                align="center",
            ),
            rx.hstack(
            rx.heading("morcosfariasm@gmail.com", font_size="min(3vw, 16px)"),
            marginLeft="0.5em",
            marginRight="0.5em",
            color="white",
            fontWeight="semibold",
            #text_shadow="4px 8px 12px white",
            text_border="2px solid black",
        ),
            #rx.link(
            #    rx.image(src="gmail.png", radius="full"),
            #    href="mailto:morcosfariasm@gmail.com",
            #    target="_blank",
            #    maxWidth="48px",
            #    width="100%",
            #    maxHeight="48px",
            #    height="100%",
            #    align="center",
            #),
            size="3",
            fontWeight="semibold",
            alignItems="center",
            #justifyContent="space-between",
            align="center",
            alignContent="center",
        ),
        as_="nav",
        class_name="navbar",
        position="fixed",
        top="0px",
        bot="20px",
        placeholder="white",
        #background_color="5px 10px 20px rgba(100, 200, 300, 400)",
        background_color="rgba(0, 0, 0, 0.5)",
        box_shadow= "5px 10px 20px rgba(0, 0, 0, 0.5)",
        border= "0 1px solid rgba(0, 0, 0, 0)",
        backdrop_filter= "blur(50px)",
        padding="1em",
        height="3em",
        width="100%",
        z_index="5",
        align="center",
        alignItems="center",
        justifyContent="center",
        alignContent="center",
        
    )
