import reflex as rx
from rx_carousel.carousel import carousel

def projects() -> rx.Component:
    return rx.container(
        rx.box(
            rx.heading(
                "Projects",
                as_="h2",
                id="projects",
                color="dark",
                size="7",
                #textColor="white",
                variant="projects",
                textDecorationThickness="2.5px",
                fontWeight="bold",
                pb="2",
                marginTop="40px !important",
                align="center",
            ),
            mt="5",
            align="center",
        ),
        id="projects",
        delay="0.1",
        mt="10",
        pt="20",
        textColor="white",
        align="center",
    )
        
    
    
def first_project() -> rx.Component:
    return carousel(
            rx.image(
                src="icl_ums_c1.jpg",
                alt="Project 1",
                placeholder="blur",
                #border_radius="2.5%",
                #border="2px solid white",
                width="800px",
                maxWidth="800px",
                height="400px",
            ),
            rx.image(
                src="icl_ums_c2.jpg",
                alt="Project 2",
                placeholder="blur",
                #border_radius="5%",
                #border="2px solid white",
                width="800px",
                maxWidth="800px",
                height="400px",
            ),
        marginBottom="20px",
        height="400px",
        width="100%",
        button_prev_border_radius="50%",
        button_next_border_radius="50%",
        show_buttons=True,  
        show_indicators=True,
        show_status=True,
        show_navigation=True,
        show_navigation_on_hover=True,
        show_navigation_on_focus=True,
        button_prev_text="Previous",
        button_next_text="Next",
        button_prev_color="white",
        button_next_color="white",
        button_prev_bg="blue",
        button_next_bg="blue",
        button_prev_size="lg",
        button_next_size="lg",
        button_prev_top="10%",
        button_next_top="10%",
        button_prev_left="10px",
        button_next_right="10px",
        #border="2px solid white",
        #borderRadius="lg",
    )
    
def second_project() -> rx.Component:
    return carousel(
            rx.image(
                src="forky.jpg",
                alt="Project 2",
                placeholder="blur",
                #border_radius="2.5%",
                #border="2px solid white",
                width="100%",
                maxWidth="900px",
                height="400px",
            ),
            rx.image(
                src="forky.jpg",
                alt="Project 2",
                placeholder="blur",
                #border_radius="5%",
                #border="2px solid white",
                width="100%",
                maxWidth="900px",
                height="400px",
            ),
        height="400px",
        width="100%",
        button_prev_border_radius="50%",
        button_next_border_radius="50%",
        show_buttons=True,  
        show_indicators=True,
        show_status=True,
        show_navigation=True,
        show_navigation_on_hover=True,
        show_navigation_on_focus=True,
        button_prev_text="Previous",
        button_next_text="Next",
        button_prev_color="white",
        button_next_color="white",
        button_prev_bg="blue",
        button_next_bg="blue",
        button_prev_size="lg",
        button_next_size="lg",
        button_prev_top="10%",
        button_next_top="10%",
        button_prev_left="10px",
        button_next_right="10px",
        #border="2px solid white",
        #borderRadius="lg",
    )